#!/bin/bash

clear

if [ $# -eq 0 ]; then
  echo "Usage: $0 <filename>"
  exit 1
fi

filename="$1"

# Check if the file already exists
if [ -e "$filename.c" ]; then
  echo "File '$filename.c' already exists."
  exit 1
fi

# If the provided filename doesn't end with '.c', add it
if [[ "$filename" != *.c ]]; then
  filename="$filename.c"
fi

# Create the C template code
cat <<EOF > "$filename"
#include <stdio.h>

/**
 * m - Program
 * Return: None
 */

int m(void)
{
	return (0);
}

EOF

# Open the file in vi
vi "$filename"

# Run the Betty checker
betty "$filename"

echo "The commands run are"
echo "clear"
echo "vi $filename"
echo "betty $filename"
